DANGER = [
    "SESSION",
    "HEROKU_API",
    "base64",
    "bash",
    "get_me()",
    "phone",
    "REDIS_PASSWORD",
    "load_modules",
    "load_panda",
    "load_PandaX_v20",
    "os.system",
    "sys.stdout",
    "sys.stderr",
    "subprocess",
    "await locals()",
    "aexec",
    ".session.save()",
]
